language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
services: xvfb
matrix:
  include:
    - name: "Python 3.8 on xenial"
      python: '3.8'
      dist: xenial
    - name: "Python 3.8 on bionic"
      python: '3.8'
      dist: bionic
    - name: "Python 3.7 on macOS"
      python: '3.7'
      os: osx
      osx_image: xcode11.2
      language: minimal
      before_install: sw_vers
    - name: "Python 3.8 on Windows"
      python: '3.8'
      os: windows
      language: bash
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  allow_failures:
    - os: windows
  fast_fail: true
addons:
  apt:
    update: true
    packages:
    - freeglut3-dev
    - python3-gi
    - python3-gi-cairo
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt -r requirements_dev.txt
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then pytest --ignore=tests/unit2; fi  # TODO: remove the --ignore
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python3 -m mypy -p arcade; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python3 -m pytest --cov; coveralls; fi
# after_success: coveralls
