environment:
  PASS:
    secure: "ni4lUD07eVM5LR2qdot9b/eJZTf89cl0st/9/9wRcaw="
  USER:
    secure: "vqkRNxewT2z/PD+0VquHTA=="
  COVERALLS_REPO_TOKEN:
    secure: rAutnXmt6Uqrtbi7shwIii97qFj0dxwjhRRno6vlqL+Oa/StGUo2oZW8J8g0VVwx
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "32"


install:
  - "%PYTHON%\\Scripts\\pip.exe install wheel twine pillow pyglet coverage coveralls pytest"

build_script:
  - "%PYTHON%\\python.exe setup.py build sdist bdist bdist_wheel"

test_script:
  - "%PYTHON%\\Scripts\\coverage run --source=arcade setup.py test"

artifacts:
  - path: dist\*

on_success:
#  - "%PYTHON%\\Scripts\\coverage report"
#  - "%PYTHON%\\Scripts\\coveralls"
#  - "%PYTHON%/Scripts/twine upload -u %USER% -p %PASS% -r pypi dist/*"
